openapi: 3.0.3
info:
    title: Hot sause shop API
    description: |-
        This is an API created during the Rolling Scopes "AWS with Node.js" course
    contact:
        email: teenwolf23299@gmail.com

    version: 1.0.1
servers:
    - url: https://ml8i1o232a.execute-api.eu-west-1.amazonaws.com/dev/
paths:
    /products:
        get:
            description: get all available products
            responses:
                '200':
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/products'
        post:
            description: post new product
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                title:
                                    type: string
                                    example: 'product title'
                                description:
                                    type: string
                                    example: 'product description'
                                count:
                                    type: number
                                    example: 10
                                price:
                                    type: integer
                                    example: 12.20
            responses:
                '201':
                    description: 'successfully created'

    /products/{productId}:
        get:
            description: get product by ID
            parameters:
                - name: productId
                  in: path
                  description: id of the product
                  required: true
                  schema:
                      type: string
                      example: '1111-1111-1111-111'
            responses:
                '200':
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/product'
                '404':
                    description: product with specified ID not found
components:
    schemas:
        products:
            type: array
            items:
                properties:
                    id:
                        type: string
                        example: '123'
                    title:
                        type: string
                        example: 'product title'
                    description:
                        type: string
                        example: 'product description'
                    count:
                        type: number
                        example: 10
                    price:
                        type: integer
                        example: 12.20
        product:
            type: object
            properties:
                id:
                    type: string
                    example: '123'
                title:
                    type: string
                    example: 'product title'
                description:
                    type: string
                    example: 'product description'
                count:
                    type: number
                    example: 10
                price:
                    type: integer
                    example: 12.20
